package com.group5.springboot.dto.cart;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;

/**
 * <li>A custom DTO class to receive ECPay payment result payload, whose structure
 * is reverse-engineered from {@link Map} enumeration.</li>
 * <li>Might have out-of-box duplicate offered in ECPay; made mainly for learning
 * purpose and to replace ambiguous {@link Map} with explicit type.</li>
 **/
public final class ECPayPaymentResult {
	private final String CustomField1;
	private final String CustomField2;
	private final String CustomField3;
	private final String CustomField4;
	private final String MerchantID; // generated by ECPay
	private final String MerchantTradeNo;
	private final String PaymentDate;
	private final String PaymentType;
	private final String PaymentTypeChargeFee;
	private final String RtnCode;
	private final String RtnMsg;
	private final String SimulatePaid;
	private final String StoreID;
	private final String TradeAmt;
	private final String TradeDate;
	private final String TradeNo;
	private final String CheckMacValue;


	@JsonCreator
	public ECPayPaymentResult(String CustomField1, String CustomField2, String CustomField3, String CustomField4, String MerchantID, String MerchantTradeNo, String PaymentDate, String PaymentType, String PaymentTypeChargeFee, String RtnCode, String RtnMsg, String SimulatePaid, String StoreID, String TradeAmt, String TradeDate, String TradeNo, String CheckMacValue) {
		this.CustomField1 = CustomField1;
		this.CustomField2 = CustomField2;
		this.CustomField3 = CustomField3;
		this.CustomField4 = CustomField4;
		this.MerchantID = MerchantID;
		this.MerchantTradeNo = MerchantTradeNo;
		this.PaymentDate = PaymentDate;
		this.PaymentType = PaymentType;
		this.PaymentTypeChargeFee = PaymentTypeChargeFee;
		this.RtnCode = RtnCode;
		this.RtnMsg = RtnMsg;
		this.SimulatePaid = SimulatePaid;
		this.StoreID = StoreID;
		this.TradeAmt = TradeAmt;
		this.TradeDate = TradeDate;
		this.TradeNo = TradeNo;
		this.CheckMacValue = CheckMacValue;
	}

	private ECPayPaymentResult(Builder builder) {
		CustomField1 = builder.CustomField1;
		CustomField2 = builder.CustomField2;
		CustomField3 = builder.CustomField3;
		CustomField4 = builder.CustomField4;
		MerchantID = builder.MerchantID;
		MerchantTradeNo = builder.MerchantTradeNo;
		PaymentDate = builder.PaymentDate;
		PaymentType = builder.PaymentType;
		PaymentTypeChargeFee = builder.PaymentTypeChargeFee;
		RtnCode = builder.RtnCode;
		RtnMsg = builder.RtnMsg;
		SimulatePaid = builder.SimulatePaid;
		StoreID = builder.StoreID;
		TradeAmt = builder.TradeAmt;
		TradeDate = builder.TradeDate;
		TradeNo = builder.TradeNo;
		CheckMacValue = builder.CheckMacValue;
	}


	// getters
	// explicit @JsonProperty since Jackson parses getter names during serialization,
	// and #getCustomField1 gets parsed into customField1 in JSON, not CustomField1
	@JsonProperty("CustomField1")
	public String getCustomField1() {
		return CustomField1;
	}

	@JsonProperty("CustomField2")
	public String getCustomField2() {
		return CustomField2;
	}

	@JsonProperty("CustomField3")
	public String getCustomField3() {
		return CustomField3;
	}

	@JsonProperty("CustomField4")
	public String getCustomField4() {
		return CustomField4;
	}

	@JsonProperty("MerchantID")
	public String getMerchantID() {
		return MerchantID;
	}

	@JsonProperty("MerchantTradeNo")
	public String getMerchantTradeNo() {
		return MerchantTradeNo;
	}

	@JsonProperty("PaymentDate")
	public String getPaymentDate() {
		return PaymentDate;
	}

	@JsonProperty("PaymentType")
	public String getPaymentType() {
		return PaymentType;
	}

	@JsonProperty("PaymentTypeChargeFee")
	public String getPaymentTypeChargeFee() {
		return PaymentTypeChargeFee;
	}

	@JsonProperty("RtnCode")
	public String getRtnCode() {
		return RtnCode;
	}

	@JsonProperty("RtnMsg")
	public String getRtnMsg() {
		return RtnMsg;
	}

	@JsonProperty("SimulatePaid")
	public String getSimulatePaid() {
		return SimulatePaid;
	}

	@JsonProperty("StoreID")
	public String getStoreID() {
		return StoreID;
	}

	@JsonProperty("TradeAmt")
	public String getTradeAmt() {
		return TradeAmt;
	}

	@JsonProperty("TradeDate")
	public String getTradeDate() {
		return TradeDate;
	}

	@JsonProperty("TradeNo")
	public String getTradeNo() {
		return TradeNo;
	}

	@JsonProperty("CheckMacValue")
	public String getCheckMacValue() {
		return CheckMacValue;
	}


	@Override
	public String toString() {
		return "ECPayPaymentResult{" +
			   "CustomField1='" + CustomField1 + '\'' +
			   ", CustomField2='" + CustomField2 + '\'' +
			   ", CustomField3='" + CustomField3 + '\'' +
			   ", CustomField4='" + CustomField4 + '\'' +
			   ", MerchantID='" + MerchantID + '\'' +
			   ", MerchantTradeNo='" + MerchantTradeNo + '\'' +
			   ", PaymentDate='" + PaymentDate + '\'' +
			   ", PaymentType='" + PaymentType + '\'' +
			   ", PaymentTypeChargeFee='" + PaymentTypeChargeFee + '\'' +
			   ", RtnCode='" + RtnCode + '\'' +
			   ", RtnMsg='" + RtnMsg + '\'' +
			   ", SimulatePaid='" + SimulatePaid + '\'' +
			   ", StoreID='" + StoreID + '\'' +
			   ", TradeAmt='" + TradeAmt + '\'' +
			   ", TradeDate='" + TradeDate + '\'' +
			   ", TradeNo='" + TradeNo + '\'' +
			   ", CheckMacValue='" + CheckMacValue + '\'' +
			   '}';
	}


	public static final class Builder {
		private String CustomField1;
		private String CustomField2;
		private String CustomField3;
		private String CustomField4;
		private String MerchantID;
		private String MerchantTradeNo;
		private String PaymentDate;
		private String PaymentType;
		private String PaymentTypeChargeFee;
		private String RtnCode;
		private String RtnMsg;
		private String SimulatePaid;
		private String StoreID;
		private String TradeAmt;
		private String TradeDate;
		private String TradeNo;
		private String CheckMacValue;


		private Builder() {}


		public static Builder newBuilder() {
			return new Builder();
		}

		public Builder CustomField1(String val) {
			CustomField1 = val;
			return this;
		}

		public Builder CustomField2(String val) {
			CustomField2 = val;
			return this;
		}

		public Builder CustomField3(String val) {
			CustomField3 = val;
			return this;
		}

		public Builder CustomField4(String val) {
			CustomField4 = val;
			return this;
		}

		public Builder MerchantID(String val) {
			MerchantID = val;
			return this;
		}

		public Builder MerchantTradeNo(String val) {
			MerchantTradeNo = val;
			return this;
		}

		public Builder PaymentDate(String val) {
			PaymentDate = val;
			return this;
		}

		public Builder PaymentType(String val) {
			PaymentType = val;
			return this;
		}

		public Builder PaymentTypeChargeFee(String val) {
			PaymentTypeChargeFee = val;
			return this;
		}

		public Builder RtnCode(String val) {
			RtnCode = val;
			return this;
		}

		public Builder RtnMsg(String val) {
			RtnMsg = val;
			return this;
		}

		public Builder SimulatePaid(String val) {
			SimulatePaid = val;
			return this;
		}

		public Builder StoreID(String val) {
			StoreID = val;
			return this;
		}

		public Builder TradeAmt(String val) {
			TradeAmt = val;
			return this;
		}

		public Builder TradeDate(String val) {
			TradeDate = val;
			return this;
		}

		public Builder TradeNo(String val) {
			TradeNo = val;
			return this;
		}

		public Builder CheckMacValue(String val) {
			CheckMacValue = val;
			return this;
		}

		public ECPayPaymentResult build() {
			return new ECPayPaymentResult(this);
		}
	}


	// sample println output:
	/*
	* CustomField1 : ken
    * CustomField2 : 黃粉紅
    * CustomField3 :
    * CustomField4 :
    * MerchantID : 2000132
    * MerchantTradeNo : studiehub25122852336
    * PaymentDate : 2025/12/28 20:27:59
    * PaymentType : Credit_CreditCard
    * PaymentTypeChargeFee : 5
    * RtnCode : 1
    * RtnMsg : 交易成功
    * SimulatePaid : 0
    * StoreID :
    * TradeAmt : 200
    * TradeDate : 2025/12/28 20:27:22
    * TradeNo : 2512282027223916
    * CheckMacValue : 1BD5AD220F037028251BAB84B73A0A04F76E5B7CFD269F7A714E86189F527794
	*/
}
